version: '3.4'
services:
  transmission-openvpn:
    volumes:
      - ./vpn:/etc/openvpn/custom/
    stdin_open: true
    environment:
      - OPENVPN_PROVIDER=custom
      - OPENVPN_CONFIG=node-fr-10.protonvpn.net.udp
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - LOCAL_NETWORK=192.168.1.0/24
    cap_add:
      - NET_ADMIN
      - NET_RAW
    privileged: true
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - 8080:8080
      - 8112:8112
    image: ebrianne/docker-deluge-openvpn

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - ./plex/movies:/movies
      - ./plex/series:/series
    network_mode: service:transmission-openvpn
    restart: unless-stopped

  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400
    # devices:
    #   - /dev/dri/
    environment:
      - TZ=Europe/Paris
      - VERSION=docker
      - PUID=1000
      - PGID=1000
      - PLEX_CLAIM=${PLEX_CLAIM}

    volumes:
      - ./plex/movies:/movies
      - ./plex/series:/series

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    ports:
      - 5055:5055
    restart: unless-stopped

  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=${SWAG_DOMAIN_URL}
      - SUBDOMAINS=${SWAG_SUBDOMAIN_URLS:-www,}
      - VALIDATION=http
      - DNSPLUGIN=cloudflare #optional
      - DUCKDNSTOKEN=${DUCKDNSTOKEN} #optional
      - ONLY_SUBDOMAINS=false #optional
      - STAGING=false #optional
    volumes:
      - ./swag/config:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped

  authelia:
    image: ghcr.io/authelia/authelia:4.34.6
    container_name: authelia
    user: "1000:1000"
    environment:
      - TZ=America/New_York
    volumes:
      - ./authelia/config:/config
    restart: unless-stopped

networks:
  default:
    external: true
    name: plex_school